### ISSUE TITLE
(from bitcoind) Warning: unknown new rules activated (versionbit 2)

### ISSUE THREAD

**Issue by ikolubr** [jtoomim/p2pool#60]
Hi guys,
I'm getting that error in my p2pool.
Can anyone help?

Thank you,

**Comment by jtoomim** [comment]
#59 should resolve this. Can you test it? I haven't had a chance to do so myself yet.

**Comment by ikolubr** [comment]
> #59 should resolve this. Can you test it? I haven't had a chance to do so myself yet.

I tried on mainnet this afternoon and didn't fix the issue. -.-

**Comment by jtoomim** [comment]
Do you mean that you tried [northern-lites:mweb](https://github.com/northern-lites/p2pool_mweb/tree/mweb) and that didn't work?

**Comment by jtoomim** [comment]
Can you tell me more about your setup? Was this with Litecoin, or with a different node?

**Comment by ikolubr** [comment]
Sorry, Litecoin.
Yes, I tried with [northern-lites:mweb](https://github.com/northern-lites/p2pool_mweb/tree/mweb) on mainnet and it didn't work.

If I start p2pool as normal, it gives me this error:
```You are running a coin daemon that does not support all of the 
2022-05-07 01:24:16.980417 forking features that have been activated on this blockchain.
2022-05-07 01:24:16.980891 Consequently, your node may mine invalid blocks or may mine blocks that
2022-05-07 01:24:16.981018 are not part of the Nakamoto consensus blockchain.
2022-05-07 01:24:16.981123 
2022-05-07 01:24:16.981329 Missing fork features: taproot, mweb
2022-05-07 01:24:16.981492 
2022-05-07 01:24:16.981651 If you know what you're doing, this error may be overridden by running p2pool
2022-05-07 01:24:16.981786 with the '--allow-obsolete-bitcoind' command-line option.```

When I add the '--allow-obsolete-bitcoind', it keeps giving me the '(from bitcoind) Warning: unknown new rules activated (versionbit 2)' error.

**Comment by jtoomim** [comment]
Are you using an obsolete version of litecoind that doesn't support the coming Taproot and MWEB upgrades?

**Comment by ikolubr** [comment]
Nope. Running latest stable version: v0.18.1 (I even tried with the v0.21.1rc1, but still no success).

**Comment by jtoomim** [comment]
The latest stable version (v0.18.1) is 2 years old and does not support the coming Taproot and MWEB upgrades. The other version you tried (0.21.1rc1) is 5.5 months old. You need to be using one of the 0.21.2 release candidates. Currently, the most recent binary is 0.21.2rc6, but the final 0.21.2 has been tagged and should be released soon.

https://dev.litecoin.org/

**Comment by ikolubr** [comment]
Just saw that... Thank you for your time... compiling 0.21.2... hoping for the best.

**Comment by jtoomim** [comment]
Actually, that was probably premature. Still needs to be tested.

**Comment by ikolubr** [comment]
Ok, have been running for 1 hour on mainnet. All looking good! ;)
Thank you again.
